// Code generated by protoc-gen-go.
// source: authentication.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	authentication.proto

It has these top-level messages:
	AuthenticationRequest
	AuthenticationResponse
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// AuthenticationRequest is the initial request
// client makes to start session with server
type AuthenticationRequest struct {
	// UserName name of the client
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	// MethodName PUBLIC_KEY or PASSWORD
	MethodName string `protobuf:"bytes,2,opt,name=MethodName,json=methodName" json:"MethodName,omitempty"`
	// PublicKey of the client
	PublicKey []byte `protobuf:"bytes,3,opt,name=PublicKey,json=publicKey,proto3" json:"PublicKey,omitempty"`
}

func (m *AuthenticationRequest) Reset()                    { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()               {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// AuthenticationResponse is the server reponse to AuthenticationRequest
type AuthenticationResponse struct {
	// MethodName that the server expects
	MethodName string `protobuf:"bytes,1,opt,name=MethodName,json=methodName" json:"MethodName,omitempty"`
	// PublicKey of the server
	PublicKey []byte `protobuf:"bytes,2,opt,name=PublicKey,json=publicKey,proto3" json:"PublicKey,omitempty"`
}

func (m *AuthenticationResponse) Reset()                    { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()               {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*AuthenticationRequest)(nil), "wire.AuthenticationRequest")
	proto.RegisterType((*AuthenticationResponse)(nil), "wire.AuthenticationResponse")
}

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0x2d, 0xc9,
	0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x29, 0xcf, 0x2c, 0x4a, 0x55, 0x2a, 0xe4, 0x12, 0x75, 0x44, 0x91, 0x0d, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x08, 0x2d, 0x4e, 0x2d, 0xf2, 0x4b, 0xcc, 0x4d,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x28, 0x85, 0xf2, 0x85, 0xe4, 0xb8, 0xb8, 0x7c,
	0x53, 0x4b, 0x32, 0xf2, 0x53, 0xc0, 0xb2, 0x4c, 0x60, 0x59, 0xae, 0x5c, 0xb8, 0x88, 0x90, 0x0c,
	0x17, 0x67, 0x40, 0x69, 0x52, 0x4e, 0x66, 0xb2, 0x77, 0x6a, 0xa5, 0x04, 0x33, 0x50, 0x9a, 0x27,
	0x88, 0xb3, 0x00, 0x26, 0xa0, 0x14, 0xc6, 0x25, 0x86, 0x6e, 0x65, 0x71, 0x41, 0x7e, 0x5e, 0x31,
	0xba, 0xb9, 0x8c, 0xf8, 0xcd, 0x65, 0x42, 0x33, 0x37, 0x89, 0x0d, 0xec, 0x2f, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x71, 0xcb, 0x84, 0x65, 0xef, 0x00, 0x00, 0x00,
}
